#ifndef GLOBALDEFINITIONS_H
#define GLOBALDEFINITIONS_H

#define MAXNAMELENGTH 64
#define MAXVALIDYEAR 3000
#define PHONENUMBERLENGTH 10
#define MAXIDENTIFIERLENGTH 16
#define CARRIERLENGTH 3
#define MAXGROUPLENGTH 20
#define MAXPOLICYLENGTH 20
#define MAXRXQUANTITY 99999
#define MAXFILEIDLENGTH 64

#endif
